# Generated by Django 4.2.30 on 2026-06-27 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('winning_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_results', to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_results', to='draws.draw')),
                ('draw_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_results', to='draws.drawschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['draw', 'draw_schedule', 'draw_date'], name='winners_win_draw_id_2369bf_idx'), models.Index(fields=['winning_number'], name='winners_win_winning_e9aed3_idx')],
                'unique_together': {('draw', 'draw_schedule', 'draw_date', 'winning_number')},
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=160)),
                ('winning_number', models.CharField(max_length=10)),
                ('amount_bet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='sales.sale')),
                ('sale_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='sales.saleitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'is_paid'], name='winners_win_seller__99f2f6_idx'), models.Index(fields=['winning_number'], name='winners_win_winning_afc205_idx')],
            },
        ),
    ]
