# Generated by Django 4.2.30 on 2026-07-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='perm_closures',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='perm_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='perm_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='perm_winners',
            field=models.BooleanField(default=True),
        ),
    ]
