# Generated by Django 4.2.30 on 2026-06-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=160)),
                ('draw_date', models.DateField()),
                ('sale_datetime', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_possible_prize', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('CLOSED', 'Cerrada')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='draws.draw')),
                ('draw_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='draws.drawschedule')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-sale_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('possible_prize', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='sales_salei_number_fb88fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', 'draw_date'], name='sales_sale_seller__db74db_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['draw', 'draw_schedule', 'draw_date'], name='sales_sale_draw_id_cbd260_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
    ]
