# Generated by Django 4.2.30 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_dailyclosure_dailyclosure_unique_seller_closure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosure',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
